apiVersion: apps/v1
kind: Deployment
metadata:
  name: ymlpractise1
spec:
  selector:
    matchLabels:
      app: ymlpractise1
  replicas: 2
  template:
    metadata:
      labels:
        app: ymlpractise1
    spec:
      containers:
      - name: ymlpractise1
        image: srijafirst.azurecr.io/ymlpractise
        ports:
        - containerPort: 80
apiVersion: v1
kind: Service
metadata:
  name: ymlpractise1
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: ymlpractise1
